### ISSUE TITLE
The evaluation metrics

### ISSUE THREAD

**Issue by ghost** [ldkong1205/LaserMix#11]
Dear author, 

I'm wondering how you evaluate the model. In detail, do you extract the voxel/range prediction based on the voxel/range coordinate and compare them in point-wise level or you just simply compare them with voxel/range labels directly.

Regards,

**Comment by ldkong1205** [comment]
Hi @RyuSangwook, thanks for asking!

For your question: The original reporting in the CVPR paper adopts voxel/range predictions directly. In our new implementation on `MMDetection3D`, everything goes to the point level, that is, the predictions of both voxel and range view have been re-mapped to the point-level ones. We suggest you stick with the new implementation since it is more consistent.

Let me know if you have further questions!

**Comment by ldkong1205** [comment]
Hi @RyuSangwook, the previous implementation is stale and we do not include it here. Please adjust the configuration based on the current implementation. Thanks!

**Comment by ldkong1205** [comment]
> Ok, so can you demonstrate the difference between the "stale" version and the current version, as the different evaluation will definitely lead to inconsistent results.
> 
> Most importantly, I can't find anything about range in the lasermix configuration, as it is only for cylinder3d https://github.com/ldkong1205/LaserMix/blob/main/configs/lasermix/lasermix_cy3d_semi_semantickitti_1.py.

Hi @RyuSangwook, sure! The "stale" version is built based on the Cylinder3D codebase, while the current version is rebuilt based on MMDetection3D. There are notable differences between these two implementations, for example, the current one uses spconv v2 instead of the v1 in Cylinder3D. The different evaluations indeed led to inconsistent results but, luckily, our new implementation achieved even better results than the one reported in the paper. Therefore, I suggest you follow our MMDetection3D implementation and report at the point level instead of voxel or range view.

For your second question: the config file you linked is for the voxel version using Cylinder3D. The range view version is based on CENet. We will support this (and many other backbones) in our next update. Please stay tuned!
