### ISSUE TITLE
Question about the requirement of GPUs

### ISSUE THREAD

**Issue by Hugo-cell111** [ldkong1205/LaserMix#12]
Hi! How many GPUs and what kind of GPUs are needed in semi-supervised point-cloud segmentation task?

**Comment by ldkong1205** [comment]
Hi @Hugo-cell111, thanks for your interest in this work!

For your question:
- It depends on which point cloud segmentation backbone you are going to use.
- As mentioned in the paper, our approach consumes 2x memory compared to the fully-supervised methods, and the training speed will not be affected.
- Since our codebase is based on `MMDetection3D`, you can refer to the training time of different fully-supervised LiDAR segmentation models from the [benchmark](https://github.com/open-mmlab/mmdetection3d). Here I list some statistics for you:

| Method | Backend | Memory | Training Time | FPS |
| :-: | :-: | :-: | :-: | :-: |
| MinkUNet18-W16 | `torchsparse` | 3.4 GB | - | - |
| MinkUNet34-W32 | `minkowski engine` | 11.5 GB | 6.5 hours | 12.2 |
| MinkUNet34-W32 | `spconv` | 6.7 GB | 2.0 hours | 14.6 |
| Cylinder3D | `spconv` |  10.2 GB | - | - |

- The experiments use 8 GPUs. You can adopt the number of machines to use based on these statistics.

**Comment by ldkong1205** [comment]
Hi @Hugo-cell111, hope the above answer resolves your question. Free feel to let us know if you have further questions!
