### ISSUE TITLE
Training config for the nuScenes and ScribbleKITTI dataset.

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#13]
Hi, thanks for your nice work!
Do you have any plan to release the config file of the lasermix for the nuScenes and ScribbleKITTI dataset?

**Comment by azhuantou** [comment]
Thanks for your reply! @ldkong1205 
But the corresponding files (e.g., semi_nuscenes_seg.py) are not updeted.  
Could you please upload the missing files?

**Comment by ldkong1205** [comment]
Hi @azhuantou,

Sorry for the confusion. The missing files are now uploaded to the codebase. Could you try and let me know if they work?

By the way, for the ScribbleKITTI dataset, since it shares the same data with SemanticKITTI (the only difference is the labels), you can just adopt the scripts from SemanticKITTI and modify the file paths.

**Comment by azhuantou** [comment]
Thans for your timely reply! @ldkong1205 
The corresponding pkl files (e.g., nuscenes_infos_train.20.pkl) for the nuscenes data are missing, and I can not find in https://drive.google.com/drive/folders/1PInw2Wvt-vgNzOxlSd2EiDANrTsWV7w1.

**Comment by ldkong1205** [comment]
Hi @azhuantou, the `nuscenes_infos_train.pkl` has a relatively large size. We recommend generating it locally using [generate_nus_pkl.py](https://github.com/ldkong1205/LaserMix/blob/main/tools/generate_nus_pkl.py).

After this, you can use [generate_nus_semi_pkl.py](https://github.com/ldkong1205/LaserMix/blob/main/tools/generate_nus_semi_pkl.py) to generate the corresponding files for semi-supervised learning. These .pkl file will have a similar format as those used for SemanticKITTI/ScribbleKITTI.

**Comment by azhuantou** [comment]
Thank you for your patient responses. @ldkong1205 
However, frame indices for different ratios are not provided (e.g., nuscenes_1pct.txt), and this file might be necessary for reproducing your results. By the way, could you please let me know the sizes of nuscenes_infos_train.pkl and nuscenes_infos_val.pkl? 
Looking forward to your reply.

**Comment by ldkong1205** [comment]
Hi @azhuantou, the sizes of the original `nuscenes_infos_train.pkl` and `nuscenes_infos_val.pkl` files are listed as follows:

| File | Size |
| :- | :-: |
| `nuscenes_infos_train.pkl` | 469 MB |
| `nuscenes_infos_val.pkl` | 98 MB |

This is because the original nuScenes `.pkl` files contain information not only for lidarseg but also for 3D detection and multi-view images.

We have managed to generate `.pkl` files for our lidarseg task only. You can download them from [this]() Google Drive. The dataset structure can be found at [DATA_PREPARE.md](https://github.com/ldkong1205/LaserMix/blob/main/docs/DATA_PREPARE.md).

The updated files' sizes are as follows:

| File | Size |
| :- | :-: |
| `nuscenes_infos_train.pkl` | 5.7 MB |
| `nuscenes_infos_val.pkl` | 1.2 MB |
| `nuscenes_infos_train.1.pkl` | 56 KB |
| `nuscenes_infos_train.1-unlabeled.pkl` | 5.6 MB |
| `nuscenes_infos_train.10.pkl` | 565 KB |
| `nuscenes_infos_train.10-unlabeled.pkl` | 5.1 MB |
| `nuscenes_infos_train.20.pkl` | 1.1 MB |
| `nuscenes_infos_train.20-unlabeled.pkl` | 4.5 MB |
| `nuscenes_infos_train.50.pkl` | 2.8 MB |
| `nuscenes_infos_train.50-unlabeled.pkl` | 2.8 MB |

**Comment by azhuantou** [comment]
Thank you so much! I will try the next step.

**Comment by ldkong1205** [comment]
> Thank you so much! I will try the next step.

Sure! Feel free to reach out again if you have other questions.

**Comment by azhuantou** [comment]
Hi, @ldkong1205 @Xiangxu-0103  could you please show the training log file (lasermix_cy3d_semi_nuscenes_10.py) for the nuScenes dataset. I can not reproduce the results claimed in your paper, so I want to find out by comparing whether I did any steps wrong.

**Comment by ldkong1205** [comment]
Hi @azhuantou, I attached one log file below for you to check. Without tuning the default parameters, you should at least reach the reported scores with <1% mIoU variance. Let us know if you find any problems with your reproduction. Thanks!

[lasermix_cy3d_4xb4_semi_nuscenes_10.log](https://github.com/ldkong1205/LaserMix/files/13233742/lasermix_cy3d_4xb4_semi_nuscenes_10.log)
