### ISSUE TITLE
Code for LaserMix based on FIDNet.

### ISSUE THREAD

**Issue by azhuantou** [ldkong1205/LaserMix#26]
Thanks for your nice work!
Do you have a plan to release code for FIDNet?

**Comment by ldkong1205** [comment]
Hi @azhuantou, sorry for the late reply!

Currently, we do not have a plan to support FIDNet, since its performance falls behind the trend of range view LiDAR segmentation.

We have supported [CENet](https://github.com/ldkong1205/LaserMix/tree/main/projects/CENet), a better version of FIDNet in terms of accuracy and efficiency.

We would also like to introduce [FRNet](https://github.com/Xiangxu-0103/FRNet), the current state-of-the-art range view LiDAR segmentation model that achieves promising semi-supervised learning results on SemanticKITTI and nuScenes. Code and checkpoints are available for downloading.

**Comment by azhuantou** [comment]
Thank you very much for your reply!
I will try the CENet and FRNet later.
